#夢削除
open('other_txt/yumewogenzituni/yumewogenzituni_day_main_total.txt', 'w').write("±0")
open('other_txt/yumewogenzituni/yumewogenzituni_day_win_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_day_lose_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_day_draw_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_before_main_total.txt', 'w').write("±0")
open('other_txt/yumewogenzituni/yumewogenzituni_before_win_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_before_lose_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_before_draw_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_after_main_total.txt', 'w').write("±0")
open('other_txt/yumewogenzituni/yumewogenzituni_after_win_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_after_lose_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_after_draw_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_nightsession_main_total.txt', 'w').write("±0")
open('other_txt/yumewogenzituni/yumewogenzituni_nightsession_win_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_nightsession_lose_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_nightsession_draw_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_overnight2_main_total.txt', 'w').write("±0")
open('other_txt/yumewogenzituni/yumewogenzituni_overnight2_win_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_overnight2_lose_total.txt', 'w').write("0")
open('other_txt/yumewogenzituni/yumewogenzituni_overnight2_draw_total.txt', 'w').write("0")

#サクセス削除
open('other_txt/sakusesunikki/sakusesunikki_day_main_total.txt', 'w').write("±0")
open('other_txt/sakusesunikki/sakusesunikki_nightsession_main_total.txt', 'w').write("±0")
open('other_txt/sakusesunikki/sakusesunikki_overnight2_main_total.txt', 'w').write("±0")
open('other_txt/sakusesunikki/sakusesunikki_day_sub_total.txt', 'w').write("±0")
open('other_txt/sakusesunikki/sakusesunikki_nightsession_sub_total.txt', 'w').write("±0")
open('other_txt/sakusesunikki/sakusesunikki_overnight2_sub_total.txt', 'w').write("±0")

#先物日経削除
open('other_txt/sakimononikkei/sakimononikkei_day_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_before_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_after_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_nightsession_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight1_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight2_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_day_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_before_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_after_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_nightsession_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight1_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight2_sub_total.txt', 'w').write("±0")

#先物投資削除
open('other_txt/investing/investing_before_main_total.txt', 'w').write("±0")
open('other_txt/investing/investing_before_win_total.txt', 'w').write("0")
open('other_txt/investing/investing_before_lose_total.txt', 'w').write("0")
open('other_txt/investing/investing_before_draw_total.txt', 'w').write("0")
open('other_txt/investing/investing_after_main_total.txt', 'w').write("±0")
open('other_txt/investing/investing_after_win_total.txt', 'w').write("0")
open('other_txt/investing/investing_after_lose_total.txt', 'w').write("0")
open('other_txt/investing/investing_after_draw_total.txt', 'w').write("0")
open('other_txt/investing/investing_c_main_total.txt', 'w').write("±0")
open('other_txt/investing/investing_c_win_total.txt', 'w').write("0")
open('other_txt/investing/investing_c_lose_total.txt', 'w').write("0")
open('other_txt/investing/investing_c_draw_total.txt', 'w').write("0")
open('other_txt/investing/investing_d_main_total.txt', 'w').write("±0")
open('other_txt/investing/investing_d_win_total.txt', 'w').write("0")
open('other_txt/investing/investing_d_lose_total.txt', 'w').write("0")
open('other_txt/investing/investing_d_draw_total.txt', 'w').write("0")

#勝ち組
open('other_txt/sakimononikkei/sakimononikkei_day_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_before_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_after_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_nightsession_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight1_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight2_main_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_day_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_before_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_after_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_nightsession_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight1_sub_total.txt', 'w').write("±0")
open('other_txt/sakimononikkei/sakimononikkei_overnight2_sub_total.txt', 'w').write("±0")

#幸運の女神
open('other_txt/megami/megami_day_main_total.txt', 'w').write("±0")
open('other_txt/megami/megami_nightsession_main_total.txt', 'w').write("±0")
open('other_txt/megami/megami_overnight2_main_total.txt', 'w').write("±0")
open('other_txt/megami/megami_day_sub_total.txt', 'w').write("±0")
open('other_txt/megami/megami_nightsession_sub_total.txt', 'w').write("±0")
open('other_txt/megami/megami_overnight2_sub_total.txt', 'w').write("±0")

#優雅な生活
open('other_txt/yuga/yuga_day_main_total.txt', 'w').write("±0")
open('other_txt/yuga/yuga_nightsession_main_total.txt', 'w').write("±0")
open('other_txt/yuga/yuga_overnight2_main_total.txt', 'w').write("±0")
open('other_txt/yuga/yuga_day_self_money_total.txt', 'w').write("±0")
open('other_txt/yuga/yuga_nightsession_self_money_total.txt', 'w').write("±0")
open('other_txt/yuga/yuga_overnight2_self_money_total.txt', 'w').write("±0")